stages:
  - deploy

variables:
  IMAGE_REPO: akitavi/flask_blog
  IMAGE_TAG: ${IMAGE_TAG:-latest}

deploy:
  stage: deploy
  image: alpine/helm:3.14.4
  script:
    - |
      set -euo pipefail
      # убедимся, что чарт на месте (полезно, если это сабмодуль)
      test -f ./charts/blog/Chart.yaml || { echo "Chart not found at ./charts/enviapp"; exit 1; }

      helm upgrade --install enviapp ./charts/blog \
        --namespace enviapp \
        --create-namespace \
        --set image.repository="$IMAGE_REPO" \
        --set image.tag="${IMAGE_TAG:-latest}"
  only:
    - main
