stages:
  - deploy

variables:
  KUBECONFIG: "$CI_PROJECT_DIR/.kube/config"
  IMAGE_REPO: docker.io/akitavi/flask_blog
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA:-latest}

deploy:
  stage: deploy
  image: alpine/helm:3.15.2
  before_script:
    - mkdir -p $CI_PROJECT_DIR/.kube
    - echo "$KUBECONFIG_FILE" | base64 -d > $KUBECONFIG
  script:
    - helm upgrade --install enviapp ./charts/enviapp \
        --namespace enviapp \
        --set image.repository=$IMAGE_REPO \
        --set image.tag=$IMAGE_TAG
