stages:
  - deploy

variables:
  IMAGE_REPO: docker.io/akitavi/flask_blog
  IMAGE_TAG: ${IMAGE_TAG:-latest}

deploy:
  stage: deploy
  image: alpine/helm:3.14.4
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" > ~/.kube/config
  script:
    - |
      set -euo pipefail
      echo "Deploying $IMAGE_REPO:$IMAGE_TAG ..."
      test -f ./charts/blog/Chart.yaml || { echo "Chart not found at ./charts/blog"; exit 1; }
      helm upgrade --install enviapp ./charts/blog --namespace enviapp --create-namespace --set image.repository="$IMAGE_REPO" --set image.tag="$IMAGE_TAG"
  only:
    - main
