replicaCount: 1

image:
  repository: akitavi/flask_blog
  tag: "latest"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  existingClaim: enviapp-static   # уже создан руками PVC

service:
  type: ClusterIP
  port: 8000

env:
  ENVI_USER: "alex"
  ENVI_DB: "envidb"
  ENVI_DB_USER: "enviapp"
  ENVI_DB_HOST: "envidb-pg.db.svc.cluster.local"
  FLASK_HOME: "/envi"
  PROD_URL: "https://m-atresh.tech"
  FLASK_APP: "main.py"
  FLASK_DEBUG: "False"

secretRef: site-secrets

accessLog:
  enabled: true
  hostPath: /var/log/nginx/access_envi.log
