replicaCount: 1

image:
  repository: akitavi/flask_blog
  tag: "latest"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  existingClaim: enviapp-static   # уже создан руками PVC

service:
  type: ClusterIP
  port: 8000

env:
  - name: ENVI_USER
    value: "alex"
  - name: ENVI_DB
    value: "envidb"
  - name: ENVI_DB_USER
    value: "enviapp"
  - name: ENVI_DB_HOST
    value: "envidb-pg.db.svc.cluster.local"
  - name: FLASK_HOME
    value: "/envi"
  - name: PROD_URL
    value: "https://m-atresh.tech"
  - name: FLASK_APP
    value: "main.py"
  - name: FLASK_DEBUG
    value: "False"

secretRef: site-secrets

accessLog:
  enabled: true
  hostPath: /var/log/nginx/access_envi.log
